import {
  ContactIcon,
  PharmacyIcon,
  PricingIcon,
  PrivacyIcon,
  TermsIcon,
} from "./constants/icons";

export const more = [
  {
    title: "Your Pharmacies",
    icon: PharmacyIcon,
    link: "UserPharmacies",
  },
  {
    title: "Pricing plans",
    icon: PricingIcon,
    link: "Pricing",
  },
  {
    title: "Privacy policy",
    icon: PrivacyIcon,
    link: "Privacy",
  },
  {
    title: "Terms of use",
    icon: TermsIcon,
    link: "Terms",
  },
  {
    title: "Contact",
    icon: ContactIcon,
    link: "Contact",
  },
];

export const categories = [
  "Diapers & Wipes",
  "Baby Feeding & Accessories",
  "Mother Care",
  "Baby Medicines & Vitamins",
  "Baby Body & Bath",
  "Baby Milk & Formula",
  "Home Aid",
  "Vaccination and Immunisation",
  "Cold, Cough & Flu",
  "Stomach & Bowel",
  "Creams and Ointments",
  "Eye, Ear, Nasal drops and Sprays",
  "Oral Care",
  "Pain Management",
  "Wound Care",
  "Men’s Health",
  "Women’s Health",
  "Antibiotics",
  "Antihypertensives",
  "Antimalarials",
  "Antifungal",
  "Mental health",
  "Antiviral",
  "Antidepressant",
  "Diabetes & Cholestrol",
  "Nausea & Vomiting",
  "Erectile Dysfunction",
  "Nausea & Vomiting",
  "Antidiarrheals",
  "Acid Reflux & Peptic Ulcers",
  "Dewormers",
  "Women’s Vitamins",
  "Kid’s Vitamins",
  "Multivitamins",
  "OraQuick HIV Self-Test",
  "Condoms",
  "Contraceptives",
  "Sexual Pleasure",
  "Tours, Travel, and Leisure",
  "Breast Milk Storage",
  "Bags",
  "Breast Pumps",
  "Disposable",
  "Feeding Bottles & Accessories",
  "Pacifiers and Teethers",
  "Formula Milk",
  "Cosmetics",
];
